Collections:
- Name: Mask R-CNN
  Metadata:
    Training Data: ICDAR2015 SCUT-CTW1500
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
    Training Resources: 1x NVIDIA A100-SXM4-80GB
    Architecture:
      - ResNet
      - FPN
      - RPN
  Paper:
    URL: https://arxiv.org/pdf/1703.06870.pdf
    Title: 'Mask R-CNN'
  README: configs/textdet/maskrcnn/README.md

Models:
  - Name: mask-rcnn_resnet50_fpn_160e_ctw1500
    In Collection: Mask R-CNN
    Config: configs/textdet/maskrcnn/mask-rcnn_resnet50_fpn_160e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Text Detection
        Dataset: CTW1500
        Metrics:
          hmean: 0.7458
    Weights: https://download.openmmlab.com/mmocr/textdet/maskrcnn/mask-rcnn_resnet50_fpn_160e_ctw1500/mask-rcnn_resnet50_fpn_160e_ctw1500_20220826_154755-ce68ee8e.pth

  - Name: mask-rcnn_resnet50_fpn_160e_icdar2015
    In Collection: Mask R-CNN
    Config: configs/textdet/maskrcnn/mask-rcnn_resnet50_fpn_160e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Text Detection
        Dataset: ICDAR2015
        Metrics:
          hmean: 0.8182
    Weights: https://download.openmmlab.com/mmocr/textdet/maskrcnn/mask-rcnn_resnet50_fpn_160e_icdar2015/mask-rcnn_resnet50_fpn_160e_icdar2015_20220826_154808-ff5c30bf.pth
